name: Test GITHUB_OUTPUT

on:
  workflow_dispatch:

jobs:
  test-output:
    runs-on: ubuntu-latest

    steps:

    - name: Set an output variable using PowerShell
      id: set-output
      run: |
        $testOutput1 = "Hello, World!"
        $testOutput2 = "Hi Simon"
        echo "testOutput1=$testOutput1" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "testOutput2=$testOutput2" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: pwsh

    - name: Use the output variable using PowerShell
      run: |
        $output1 = '${{ steps.set-output.outputs.testOutput1 }}'
        $output2 = '${{ steps.set-output.outputs.testOutput2 }}'
        Write-Host "The output variable 1 value is: $output1"
        Write-Host "The output variable 2 value is: $output2"
      shell: pwsh
