name: Test GITHUB_OUTPUT

on:
  workflow_dispatch:

jobs:
  test-output:
    runs-on: ubuntu-latest

    steps:

    - name: Set an output variable
      id: set-output
      run: |
        echo "testOutput=Hello, World!" >> $GITHUB_OUTPUT

    - name: Use the output variable
      run: |
        echo "The output variable value is: ${{ steps.set-output.outputs.testOutput }}"
